CREATE TABLE UTILISATEUR (
    ID_UTILISATEUR INTEGER NOT NULL,
    NOM VARCHAR(100) NOT NULL,
    PRENOM VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(150) NOT NULL,
    MOT_DE_PASSE VARCHAR(255) NOT NULL,
    ROLE VARCHAR(20) NOT NULL,
    DATE_CREATION DATETIME,
    PRIMARY KEY (ID_UTILISATEUR)
);

CREATE TABLE SOURCE_LOG (
    ID_SOURCE INTEGER NOT NULL,
    NOM_SOURCE VARCHAR(100) NOT NULL,
    TYPE_SOURCE VARCHAR(30) NOT NULL,
    ADRESSE_IP VARCHAR(45),
    DESCRIPTION VARCHAR(255),
    STATUT VARCHAR(20),
    DATE_AJOUT DATETIME,
    PRIMARY KEY (ID_SOURCE)
);

CREATE TABLE SERVEUR (
    ID_SERVEUR INTEGER NOT NULL,
    NOM_SERVEUR VARCHAR(100) NOT NULL,
    ADRESSE_IP VARCHAR(45) NOT NULL,
    SYSTEME_EXPLOITATION VARCHAR(100),
    LOCALISATION VARCHAR(100),
    STATUT VARCHAR(20),
    DATE_AJOUT DATETIME,
    PRIMARY KEY (ID_SERVEUR)
);

CREATE TABLE LOG_ENTREE (
    ID_LOG INTEGER NOT NULL,
    ID_SOURCE INTEGER NOT NULL,
    ID_SERVEUR INTEGER NOT NULL,
    HORODATAGE DATETIME NOT NULL,
    NIVEAU VARCHAR(20) NOT NULL,
    SERVICE VARCHAR(100),
    MESSAGE VARCHAR(255) NOT NULL,
    STATUT_TRAITEMENT VARCHAR(20),
    DATE_INSERTION DATETIME,
    PRIMARY KEY (ID_LOG)
);

CREATE TABLE ANOMALIE (
    ID_ANOMALIE INTEGER NOT NULL,
    ID_LOG INTEGER NOT NULL,
    TYPE_ANOMALIE VARCHAR(100) NOT NULL,
    SCORE DECIMAL(5,2),
    DESCRIPTION VARCHAR(255),
    DATE_DETECTION DATETIME,
    PRIMARY KEY (ID_ANOMALIE)
);

CREATE TABLE ALERTE (
    ID_ALERTE INTEGER NOT NULL,
    ID_ANOMALIE INTEGER NOT NULL,
    SEVERITE VARCHAR(20) NOT NULL,
    CANAL VARCHAR(20) NOT NULL,
    STATUT VARCHAR(20),
    DATE_ALERTE DATETIME,
    PRIMARY KEY (ID_ALERTE)
);

CREATE TABLE RAPPORT (
    ID_RAPPORT INTEGER NOT NULL,
    ID_UTILISATEUR INTEGER NOT NULL,
    TYPE_RAPPORT VARCHAR(100) NOT NULL,
    DATE_DEBUT DATE NOT NULL,
    DATE_FIN DATE NOT NULL,
    CHEMIN_FICHIER VARCHAR(255),
    DATE_GENERATION DATETIME,
    PRIMARY KEY (ID_RAPPORT)
);

CREATE TABLE COMMENTAIRE (
    ID_COMMENTAIRE INTEGER NOT NULL,
    ID_LOG INTEGER NOT NULL,
    ID_UTILISATEUR INTEGER NOT NULL,
    CONTENU VARCHAR(255) NOT NULL,
    DATE_COMMENTAIRE DATETIME,
    PRIMARY KEY (ID_COMMENTAIRE)
);

ALTER TABLE LOG_ENTREE
ADD CONSTRAINT FK_LOG_SOURCE
FOREIGN KEY (ID_SOURCE) REFERENCES SOURCE_LOG(ID_SOURCE);

ALTER TABLE LOG_ENTREE
ADD CONSTRAINT FK_LOG_SERVEUR
FOREIGN KEY (ID_SERVEUR) REFERENCES SERVEUR(ID_SERVEUR);

ALTER TABLE ANOMALIE
ADD CONSTRAINT FK_ANOMALIE_LOG
FOREIGN KEY (ID_LOG) REFERENCES LOG_ENTREE(ID_LOG);

ALTER TABLE ALERTE
ADD CONSTRAINT FK_ALERTE_ANOMALIE
FOREIGN KEY (ID_ANOMALIE) REFERENCES ANOMALIE(ID_ANOMALIE);

ALTER TABLE RAPPORT
ADD CONSTRAINT FK_RAPPORT_UTILISATEUR
FOREIGN KEY (ID_UTILISATEUR) REFERENCES UTILISATEUR(ID_UTILISATEUR);

ALTER TABLE COMMENTAIRE
ADD CONSTRAINT FK_COMMENTAIRE_LOG
FOREIGN KEY (ID_LOG) REFERENCES LOG_ENTREE(ID_LOG);

ALTER TABLE COMMENTAIRE
ADD CONSTRAINT FK_COMMENTAIRE_UTILISATEUR
FOREIGN KEY (ID_UTILISATEUR) REFERENCES UTILISATEUR(ID_UTILISATEUR);