# Generated by Django 6.0.5 on 2026-05-23 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anomalie',
            fields=[
                ('id_anomalie', models.AutoField(primary_key=True, serialize=False)),
                ('type_anomalie', models.CharField(max_length=100)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('date_detection', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Anomalie',
                'verbose_name_plural': 'Anomalies',
                'db_table': 'ANOMALIE',
            },
        ),
        migrations.CreateModel(
            name='LogEntree',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('horodatage', models.DateTimeField()),
                ('niveau', models.CharField(max_length=20)),
                ('service', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.CharField(max_length=255)),
                ('statut_traitement', models.CharField(blank=True, max_length=20, null=True)),
                ('date_insertion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Entrée de log',
                'verbose_name_plural': 'Entrées de logs',
                'db_table': 'LOG_ENTREE',
            },
        ),
        migrations.CreateModel(
            name='Serveur',
            fields=[
                ('id_serveur', models.AutoField(primary_key=True, serialize=False)),
                ('nom_serveur', models.CharField(max_length=100)),
                ('adresse_ip', models.CharField(max_length=45)),
                ('systeme_exploitation', models.CharField(blank=True, max_length=100, null=True)),
                ('localisation', models.CharField(blank=True, max_length=100, null=True)),
                ('statut', models.CharField(blank=True, max_length=20, null=True)),
                ('date_ajout', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Serveur',
                'verbose_name_plural': 'Serveurs',
                'db_table': 'SERVEUR',
            },
        ),
        migrations.CreateModel(
            name='SourceLog',
            fields=[
                ('id_source', models.AutoField(primary_key=True, serialize=False)),
                ('nom_source', models.CharField(max_length=100)),
                ('type_source', models.CharField(max_length=30)),
                ('adresse_ip', models.CharField(blank=True, max_length=45, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('statut', models.CharField(blank=True, max_length=20, null=True)),
                ('date_ajout', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Source de log',
                'verbose_name_plural': 'Sources de logs',
                'db_table': 'SOURCE_LOG',
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id_utilisateur', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=20)),
                ('date_creation', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'UTILISATEUR',
            },
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id_alerte', models.AutoField(primary_key=True, serialize=False)),
                ('severite', models.CharField(max_length=20)),
                ('canal', models.CharField(max_length=20)),
                ('statut', models.CharField(blank=True, max_length=20, null=True)),
                ('date_alerte', models.DateTimeField(blank=True, null=True)),
                ('anomalie', models.ForeignKey(db_column='ID_ANOMALIE', on_delete=django.db.models.deletion.CASCADE, to='logs.anomalie')),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
                'db_table': 'ALERTE',
            },
        ),
        migrations.AddField(
            model_name='anomalie',
            name='log',
            field=models.ForeignKey(db_column='ID_LOG', on_delete=django.db.models.deletion.CASCADE, to='logs.logentree'),
        ),
        migrations.AddField(
            model_name='logentree',
            name='serveur',
            field=models.ForeignKey(db_column='ID_SERVEUR', on_delete=django.db.models.deletion.CASCADE, to='logs.serveur'),
        ),
        migrations.AddField(
            model_name='logentree',
            name='source',
            field=models.ForeignKey(db_column='ID_SOURCE', on_delete=django.db.models.deletion.CASCADE, to='logs.sourcelog'),
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id_rapport', models.AutoField(primary_key=True, serialize=False)),
                ('type_rapport', models.CharField(max_length=100)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('chemin_fichier', models.CharField(blank=True, max_length=255, null=True)),
                ('date_generation', models.DateTimeField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(db_column='ID_UTILISATEUR', on_delete=django.db.models.deletion.CASCADE, to='logs.utilisateur')),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
                'db_table': 'RAPPORT',
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id_commentaire', models.AutoField(primary_key=True, serialize=False)),
                ('contenu', models.CharField(max_length=255)),
                ('date_commentaire', models.DateTimeField(blank=True, null=True)),
                ('log', models.ForeignKey(db_column='ID_LOG', on_delete=django.db.models.deletion.CASCADE, to='logs.logentree')),
                ('utilisateur', models.ForeignKey(db_column='ID_UTILISATEUR', on_delete=django.db.models.deletion.CASCADE, to='logs.utilisateur')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'db_table': 'COMMENTAIRE',
            },
        ),
    ]
